<?php
/**
 * OnetooneMessagesApi
 * PHP version 5
 *
 * @category Class
 * @package  MongooseIM\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MongooseIM's client REST API
 *
 * Explore MongooseIM features using our REST API.  Please keep in mind that: * All users are represented by **bare JIDs** (Jabber Identifiers such as **alice@wonderland.com**).  This is to ensure integration between the **REST API** users and regular **XMPP** users. * All requests requiring a room ID (i.e. most of the requests fired at `/room` endpoint) accept either  a bare room ID (e.g. `656c6f656c6f`) or a room JID (e.g. `656c6f656c6f@muclight.somedomain.com`).  The host part of the room JID must be the host name of a MUC light service running in user's domain. * All requests require authentication. This is to make sure the server can identify who sent the request and if it comes from an authorized user. Currently the only supported method is **Basic Auth**.
 *
 * OpenAPI spec version: 0.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MongooseIM\Client\Api;

use \MongooseIM\Client\Configuration;
use \MongooseIM\Client\ApiClient;
use \MongooseIM\Client\ApiException;
use \MongooseIM\Client\ObjectSerializer;

/**
 * OnetooneMessagesApi Class Doc Comment
 *
 * @category Class
 * @package  MongooseIM\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OnetooneMessagesApi
{

    /**
     * API Client
     *
     * @var \MongooseIM\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \MongooseIM\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\MongooseIM\Client\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://localhost:8089/api');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \MongooseIM\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \MongooseIM\Client\ApiClient $apiClient set the API client
     *
     * @return OnetooneMessagesApi
     */
    public function setApiClient(\MongooseIM\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation messagesGet
     *
     * 
     *
     * @param int $limit Specifies the maximum number of messages to be returned. Default value is 50. (optional)
     * @param int $before The timestamp in milliseconds. If set, only messages before this date will be returned. (optional)
     * @return \MongooseIM\Client\Models\RecvMessage[]
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesGet($limit = null, $before = null)
    {
        list($response) = $this->messagesGetWithHttpInfo($limit, $before);
        return $response;
    }

    /**
     * Operation messagesGetWithHttpInfo
     *
     * 
     *
     * @param int $limit Specifies the maximum number of messages to be returned. Default value is 50. (optional)
     * @param int $before The timestamp in milliseconds. If set, only messages before this date will be returned. (optional)
     * @return Array of \MongooseIM\Client\Models\RecvMessage[], HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesGetWithHttpInfo($limit = null, $before = null)
    {
        // parse inputs
        $resourcePath = "/messages";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }
        // query params
        if ($before !== null) {
            $queryParams['before'] = $this->apiClient->getSerializer()->toQueryValue($before);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\MongooseIM\Client\Models\RecvMessage[]',
                '/messages'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\MongooseIM\Client\Models\RecvMessage[]', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\MongooseIM\Client\Models\RecvMessage[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation messagesPost
     *
     * 
     *
     * @param \MongooseIM\Client\Models\SendMessage $message The message to be sent. (required)
     * @return \MongooseIM\Client\Models\ResourceID
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesPost($message)
    {
        list($response) = $this->messagesPostWithHttpInfo($message);
        return $response;
    }

    /**
     * Operation messagesPostWithHttpInfo
     *
     * 
     *
     * @param \MongooseIM\Client\Models\SendMessage $message The message to be sent. (required)
     * @return Array of \MongooseIM\Client\Models\ResourceID, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesPostWithHttpInfo($message)
    {
        // verify the required parameter 'message' is set
        if ($message === null) {
            throw new \InvalidArgumentException('Missing the required parameter $message when calling messagesPost');
        }
        // parse inputs
        $resourcePath = "/messages";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($message)) {
            $_tempBody = $message;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\MongooseIM\Client\Models\ResourceID',
                '/messages'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\MongooseIM\Client\Models\ResourceID', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\MongooseIM\Client\Models\ResourceID', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation messagesWithGet
     *
     * 
     *
     * @param string $with JID of the user with whom the messages were exchanged. Example: **alice@wonderland.com**. (required)
     * @param int $limit Specifies the maximum number of messages to be returned. Default value is 50. (optional)
     * @param int $before The timestamp in milliseconds. If set, only messages before this date will be returned. (optional)
     * @return \MongooseIM\Client\Models\RecvMessage[]
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesWithGet($with, $limit = null, $before = null)
    {
        list($response) = $this->messagesWithGetWithHttpInfo($with, $limit, $before);
        return $response;
    }

    /**
     * Operation messagesWithGetWithHttpInfo
     *
     * 
     *
     * @param string $with JID of the user with whom the messages were exchanged. Example: **alice@wonderland.com**. (required)
     * @param int $limit Specifies the maximum number of messages to be returned. Default value is 50. (optional)
     * @param int $before The timestamp in milliseconds. If set, only messages before this date will be returned. (optional)
     * @return Array of \MongooseIM\Client\Models\RecvMessage[], HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Client\ApiException on non-2xx response
     */
    public function messagesWithGetWithHttpInfo($with, $limit = null, $before = null)
    {
        // verify the required parameter 'with' is set
        if ($with === null) {
            throw new \InvalidArgumentException('Missing the required parameter $with when calling messagesWithGet');
        }
        // parse inputs
        $resourcePath = "/messages/{with}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }
        // query params
        if ($before !== null) {
            $queryParams['before'] = $this->apiClient->getSerializer()->toQueryValue($before);
        }
        // path params
        if ($with !== null) {
            $resourcePath = str_replace(
                "{" . "with" . "}",
                $this->apiClient->getSerializer()->toPathValue($with),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires HTTP basic authentication
        if (strlen($this->apiClient->getConfig()->getUsername()) !== 0 or strlen($this->apiClient->getConfig()->getPassword()) !== 0) {
            $headerParams['Authorization'] = 'Basic ' . base64_encode($this->apiClient->getConfig()->getUsername() . ":" . $this->apiClient->getConfig()->getPassword());
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\MongooseIM\Client\Models\RecvMessage[]',
                '/messages/{with}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\MongooseIM\Client\Models\RecvMessage[]', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\MongooseIM\Client\Models\RecvMessage[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
